classdef Trans_angle_axis < robotics.ros.Message
    %Trans_angle_axis MATLAB implementation of tf_system/Trans_angle_axis
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'tf_system/Trans_angle_axis' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd86204d5d465dcdbc4e0b98301bc1814' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsVector3Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Vector3') % Dispatch to MATLAB class for message type geometry_msgs/Vector3
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Translation
        AngleAxis
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Translation', [], 'AngleAxis', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'AngleAxis', 'Header', 'Translation'} % List of non-constant message properties
        ROSPropertyList = {'angle_axis', 'header', 'translation'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Trans_angle_axis(msg)
            %Trans_angle_axis Construct the message object Trans_angle_axis
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'Trans_angle_axis', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function translation = get.Translation(obj)
            %get.Translation Get the value for property Translation
            if isempty(obj.Cache.Translation)
                obj.Cache.Translation = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getTranslation);
            end
            translation = obj.Cache.Translation;
        end
        
        function set.Translation(obj, translation)
            %set.Translation Set the value for property Translation
            validateattributes(translation, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'Trans_angle_axis', 'Translation');
            
            obj.JavaMessage.setTranslation(translation.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Translation)
                obj.Cache.Translation.setJavaObject(translation.getJavaObject);
            end
        end
        
        function angleaxis = get.AngleAxis(obj)
            %get.AngleAxis Get the value for property AngleAxis
            if isempty(obj.Cache.AngleAxis)
                obj.Cache.AngleAxis = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getAngleAxis);
            end
            angleaxis = obj.Cache.AngleAxis;
        end
        
        function set.AngleAxis(obj, angleaxis)
            %set.AngleAxis Set the value for property AngleAxis
            validateattributes(angleaxis, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'Trans_angle_axis', 'AngleAxis');
            
            obj.JavaMessage.setAngleAxis(angleaxis.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.AngleAxis)
                obj.Cache.AngleAxis.setJavaObject(angleaxis.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Translation = [];
            obj.Cache.AngleAxis = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Translation = copy(obj.Translation);
            cpObj.AngleAxis = copy(obj.AngleAxis);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.Translation = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.Translation);
            obj.AngleAxis = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.AngleAxis);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.Translation = saveobj(obj.Translation);
            strObj.AngleAxis = saveobj(obj.AngleAxis);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.tf_system.Trans_angle_axis.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.tf_system.Trans_angle_axis;
            obj.reload(strObj);
        end
    end
end
